/// <reference path="./App.js" />
/// <reference path="./BCHTIX.js" />
/// <reference path="./index.js" />
/// <reference path="./App.js" />
/// <reference path="../plugins/Bootstrap 4.0/js/bootstrap.bundle.min.js" />
/// <reference path="../plugins/js/jquery.tmpl.min.js" />
/// <reference path="../plugins/js/spin.min.js" />
/// <reference path="../plugins/js/jquery-3.1.1.js" />
/// <reference path="../plugins/js/typeahead.bundle.min.js" />